name: ContainerValuePresentation
packages:
  SlideKit:
    url: https://github.com/mtj0928/SlideKit
    from: 0.3.0
targets:
  ContainerValuePresentation:
    type: application
    settings:
      base:
        INFOPLIST_FILE: ContainerValuePresentation/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.github.mtj0928.SlideGen.ContainerValuePresentation
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
    platform: macOS
    deploymentTarget: "12.0"
    sources: [ContainerValuePresentation]
    dependencies:
      - package: SlideKit
