//
//  SlideConfiguration.swift
//
//  This file is automatically generated by SlideGen
//

import SwiftUI
import SlideKit

struct SlideConfiguration {

    /// Edit the slide size.
    let size = SlideSize.standard16_9

    ///  Add your slides into the trailing closure.
    let slideIndexController = SlideIndexController {
        TitleSlide()
        ContainerValuesSlide_1()
        EnvironmentValuesSlide()
        EnvironmentValuesSlide_SampleCode()
        PreferencesSlide()
        PreferencesSlide_SampleCode()
        ContainerValuesSlide_2()
        ContainerValuesSlide_3()
        ContainerValuesSlide_SampleCode_1()
        ValueFlowSlide()
        SummarySlide()
        ReferenceSlide()
    }
}
